const $=id=>document.getElementById(id);
const file=$('file'),source=$('source'),output=$('output'),extract=$('extract'),geometry=$('geometry'),download=$('download'),status=$('status');
let loaded=false,edge=null,W=0,H=0,contours=[];
for(const id of ['threshold','blur','thickness'])$(id).addEventListener('input',e=>$(id+'Value').value=e.target.value);
file.onchange=()=>{const f=file.files[0];if(!f)return;if(!/^image\/(png|jpeg|webp)$/.test(f.type)){setStatus('Unsupported image type.',true);return}const img=new Image();img.onload=()=>{const max=1400,s=Math.min(1,max/Math.max(img.width,img.height));W=source.width=Math.round(img.width*s);H=source.height=Math.round(img.height*s);source.getContext('2d').drawImage(img,0,0,W,H);source.style.display='block';$('sourceEmpty').style.display='none';loaded=true;extract.disabled=false;geometry.disabled=download.disabled=true;setStatus('Picture loaded. Extract outlines first.');URL.revokeObjectURL(img.src)};img.src=URL.createObjectURL(f)};
extract.onclick=()=>loaded&&extractOutline();
function extractOutline(){const px=source.getContext('2d').getImageData(0,0,W,H).data;let g=new Float32Array(W*H);for(let i=0,p=0;i<px.length;i+=4,p++)g[p]=.299*px[i]+.587*px[i+1]+.114*px[i+2];for(let k=0;k<+$('blur').value;k++)g=boxBlur(g,W,H);edge=new Uint8Array(W*H);const t=+$('threshold').value;for(let y=1;y<H-1;y++)for(let x=1;x<W-1;x++){const i=y*W+x,gx=-g[i-W-1]+g[i-W+1]-2*g[i-1]+2*g[i+1]-g[i+W-1]+g[i+W+1],gy=-g[i-W-1]-2*g[i-W]-g[i-W+1]+g[i+W-1]+2*g[i+W]+g[i+W+1];edge[i]=Math.hypot(gx,gy)>=t}renderEdges();geometry.disabled=false;download.disabled=false;setStatus('Outline extraction complete. Select Analyze contours.')}
function renderEdges(){output.width=W;output.height=H;const o=output.getContext('2d'),im=o.createImageData(W,H);im.data.fill(255);for(let i=0;i<edge.length;i++)if(edge[i]){const q=i*4;im.data[q]=im.data[q+1]=im.data[q+2]=0;im.data[q+3]=255}o.putImageData(im,0,0);output.style.display='block';$('outputEmpty').style.display='none'}
geometry.onclick=()=>analyze();
function analyze(){setStatus('Finding unique contours and geometric transitions…');contours=findComponents(edge,W,H).filter(c=>c.length>=12).map(orderContour).map(c=>simplify(c,Math.max(2,Math.min(W,H)/250)));renderGeometry();download.disabled=false;const curves=contours.reduce((n,c)=>n+classify(c).curves.length,0);setStatus(contours.length+' unique contours identified; '+curves+' curved runs segmented geometrically.')}
function findComponents(map,w,h){const seen=new Uint8Array(map.length),out=[],dirs=[-1,1,-w,w,-w-1,-w+1,w-1,w+1];for(let i=0;i<map.length;i++)if(map[i]&&!seen[i]){const q=[i],c=[];seen[i]=1;while(q.length){const a=q.pop();c.push({x:a%w,y:Math.floor(a/w)});for(const d of dirs){const b=a+d;if(b>=0&&b<map.length&&map[b]&&!seen[b]&&Math.abs((b%w)-(a%w))<=1){seen[b]=1;q.push(b)}}}out.push(c)}return out}
function orderContour(points){if(points.length<2)return points;const left=points.reduce((a,b)=>b.x<a.x?b:a),unused=new Set(points.map((_,i)=>i)),path=[];let cur=points.indexOf(left);while(unused.size){unused.delete(cur);path.push(points[cur]);let best=-1,bd=Infinity;for(const i of unused){const d=dist(points[cur],points[i]);if(d<bd){bd=d;best=i}}if(best<0)break;cur=best}return path}
function simplify(p,eps){if(p.length<3)return p;const out=[p[0]];for(let i=1;i<p.length-1;i++){const a=out[out.length-1],b=p[i],c=p[i+1];if(pointLineDistance(b,a,c)>=eps)out.push(b)}out.push(p[p.length-1]);return out}
function classify(p){const corners=[0],curves=[];if(p.length<4)return{corners:[0,p.length-1],curves};let run=-1;for(let i=1;i<p.length-1;i++){const a=angle(p[i-1],p[i],p[i+1]);const curved=a>10&&a<55,corner=a>=55;if(corner){corners.push(i);if(run>=0){curves.push([run,i]);run=-1}}else if(curved&&run<0)run=i-1;else if(!curved&&run>=0){if(i-run>=3)curves.push([run,i]);run=-1}}if(run>=0)curves.push([run,p.length-1]);corners.push(p.length-1);return{corners:[...new Set(corners)],curves}}
function renderGeometry(){const o=output.getContext('2d');o.fillStyle='white';o.fillRect(0,0,W,H);o.lineWidth=Math.max(1,+$('thickness').value);o.lineCap='round';o.lineJoin='round';o.font='bold '+Math.max(11,Math.min(16,Math.min(W,H)/35))+'px Arial';let contourNo=1;for(const p of contours){if(p.length<2)continue;o.strokeStyle='black';o.beginPath();o.moveTo(p[0].x,p[0].y);for(let i=1;i<p.length;i++)o.lineTo(p[i].x,p[i].y);o.stroke();const info=classify(p),marks=[];for(const i of info.corners)marks.push({i,label:String(contourNo++)});for(const [s,e] of info.curves){for(let k=0;k<4;k++){const i=Math.round(s+(e-s)*k/3);marks.push({i,label:['a','b','c','d'][k]})}}for(const m of marks)label(o,p[m.i],m.label)}}
function label(o,p,t){const r=9;o.fillStyle='white';o.beginPath();o.arc(p.x,p.y,r,0,Math.PI*2);o.fill();o.strokeStyle='black';o.lineWidth=1;o.stroke();o.fillStyle='black';o.textAlign='center';o.textBaseline='middle';o.fillText(t,p.x,p.y)}
function angle(a,b,c){let u={x:a.x-b.x,y:a.y-b.y},v={x:c.x-b.x,y:c.y-b.y},d=(u.x*v.x+u.y*v.y)/(Math.hypot(u.x,u.y)*Math.hypot(v.x,v.y)||1);return 180-Math.acos(Math.max(-1,Math.min(1,d)))*180/Math.PI}
function pointLineDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y;if(!dx&&!dy)return dist(p,a);return Math.abs(dy*p.x-dx*p.y+b.x*a.y-b.y*a.x)/Math.hypot(dx,dy)}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function boxBlur(src,w,h){const d=new Float32Array(src.length);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let s=0,n=0;for(let yy=Math.max(0,y-1);yy<=Math.min(h-1,y+1);yy++)for(let xx=Math.max(0,x-1);xx<=Math.min(w-1,x+1);xx++){s+=src[yy*w+xx];n++}d[y*w+x]=s/n}return d}
download.onclick=()=>{const a=document.createElement('a');a.download='loftsims-geometric-contours.png';a.href=output.toDataURL('image/png');a.click()};
function setStatus(m,e=false){status.textContent=m;status.className='status'+(e?' error':'')}